version: '3.8'

services:

  app:
    container_name: react-base-v2_container
    build: /workspace/from-repo/react-base-v2
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3001:3001
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start